# Generated by Django 3.2.8 on 2021-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
